# Claude Code tools reference
# https://code.claude.com/docs/en/tools-reference

TOOL_DESCRIPTIONS: dict[str, str] = {
    "Agent":                "Spawns a subagent with its own context window to handle a task",
    "AskUserQuestion":      "Asks multiple-choice questions to gather requirements or clarify ambiguity",
    "Bash":                 "Executes shell commands in your environment",
    "CronCreate":           "Schedules a recurring or one-shot prompt within the current session",
    "CronDelete":           "Cancels a scheduled task by ID",
    "CronList":             "Lists all scheduled tasks in the session",
    "Edit":                 "Makes targeted edits to specific files",
    "EnterPlanMode":        "Switches to plan mode to design an approach before coding",
    "EnterWorktree":        "Creates an isolated git worktree and switches into it",
    "ExitPlanMode":         "Presents a plan for approval and exits plan mode",
    "ExitWorktree":         "Exits a worktree session and returns to the original directory",
    "Glob":                 "Finds files based on pattern matching",
    "Grep":                 "Searches for patterns in file contents",
    "ListMcpResourcesTool": "Lists resources exposed by connected MCP servers",
    "LSP":                  "Code intelligence via language servers",
    "NotebookEdit":         "Modifies Jupyter notebook cells",
    "Read":                 "Reads the contents of files",
    "ReadMcpResourceTool":  "Reads a specific MCP resource by URI",
    "Skill":                "Executes a skill within the main conversation",
    "TaskCreate":           "Creates a new task in the task list",
    "TaskGet":              "Retrieves full details for a specific task",
    "TaskList":             "Lists all tasks with their current status",
    "TaskOutput":           "Retrieves output from a background task",
    "TaskStop":             "Kills a running background task by ID",
    "TaskUpdate":           "Updates task status, dependencies, details, or deletes tasks",
    "TodoWrite":            "Manages the session task checklist",
    "ToolSearch":           "Searches for and loads deferred tools when tool search is enabled",
    "WebFetch":             "Fetches content from a specified URL",
    "WebSearch":            "Performs web searches",
    "Write":                "Creates or overwrites files",
}
